-drop table category;
-drop table borrower;
-drop table borrower_phone;
-drop table book_info;
-drop table book;
-drop table book_author;
-drop table book_keyword;
-drop table checked_out;
-drop table fine;
-
-drop trigger no_renew_if_overdue;
-drop trigger create_fine;
-drop trigger max_checkedout;
-drop trigger remove_book_info_when_no_copies;
